// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package com_foxelbox_foxbukkit_chatlink is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	UUID
	UserInfo
	MessageTarget
	ChatMessageOut
	ChatMessageIn
*/
package com_foxelbox_foxbukkit_chatlink

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageType int32

const (
	MessageType_TEXT        MessageType = 0
	MessageType_BLANK       MessageType = 1
	MessageType_KICK        MessageType = 2
	MessageType_PLAYERSTATE MessageType = 3
	MessageType_INJECT      MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "TEXT",
	1: "BLANK",
	2: "KICK",
	3: "PLAYERSTATE",
	4: "INJECT",
}
var MessageType_value = map[string]int32{
	"TEXT":        0,
	"BLANK":       1,
	"KICK":        2,
	"PLAYERSTATE": 3,
	"INJECT":      4,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

type TargetType int32

const (
	TargetType_ALL        TargetType = 0
	TargetType_PLAYER     TargetType = 1
	TargetType_PERMISSION TargetType = 2
	TargetType_SLACKUSER  TargetType = 3
	TargetType_SERVER     TargetType = 4
)

var TargetType_name = map[int32]string{
	0: "ALL",
	1: "PLAYER",
	2: "PERMISSION",
	3: "SLACKUSER",
	4: "SERVER",
}
var TargetType_value = map[string]int32{
	"ALL":        0,
	"PLAYER":     1,
	"PERMISSION": 2,
	"SLACKUSER":  3,
	"SERVER":     4,
}

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}
func (x TargetType) String() string {
	return proto.EnumName(TargetType_name, int32(x))
}
func (x *TargetType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TargetType_value, data, "TargetType")
	if err != nil {
		return err
	}
	*x = TargetType(value)
	return nil
}

type UUID struct {
	Msb              *int64 `protobuf:"zigzag64,1,req,name=msb" json:"msb,omitempty"`
	Lsb              *int64 `protobuf:"zigzag64,2,req,name=lsb" json:"lsb,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}

func (m *UUID) GetMsb() int64 {
	if m != nil && m.Msb != nil {
		return *m.Msb
	}
	return 0
}

func (m *UUID) GetLsb() int64 {
	if m != nil && m.Lsb != nil {
		return *m.Lsb
	}
	return 0
}

type UserInfo struct {
	Uuid             *UUID   `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}

func (m *UserInfo) GetUuid() *UUID {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type MessageTarget struct {
	Type             *TargetType `protobuf:"varint,1,req,name=type,enum=com.foxelbox.foxbukkit.chatlink.TargetType,def=0" json:"type,omitempty"`
	Filter           []string    `protobuf:"bytes,2,rep,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MessageTarget) Reset()         { *m = MessageTarget{} }
func (m *MessageTarget) String() string { return proto.CompactTextString(m) }
func (*MessageTarget) ProtoMessage()    {}

const Default_MessageTarget_Type TargetType = TargetType_ALL

func (m *MessageTarget) GetType() TargetType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_MessageTarget_Type
}

func (m *MessageTarget) GetFilter() []string {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ChatMessageOut struct {
	Id               *int64         `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Server           *string        `protobuf:"bytes,2,opt,name=server" json:"server,omitempty"`
	From             *UserInfo      `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	Timestamp        *int64         `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	Context          *UUID          `protobuf:"bytes,5,req,name=context" json:"context,omitempty"`
	FinalizeContext  *bool          `protobuf:"varint,6,opt,name=finalizeContext,def=1" json:"finalizeContext,omitempty"`
	Contents         *string        `protobuf:"bytes,7,opt,name=contents" json:"contents,omitempty"`
	Type             *MessageType   `protobuf:"varint,8,opt,name=type,enum=com.foxelbox.foxbukkit.chatlink.MessageType,def=0" json:"type,omitempty"`
	To               *MessageTarget `protobuf:"bytes,9,opt,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ChatMessageOut) Reset()         { *m = ChatMessageOut{} }
func (m *ChatMessageOut) String() string { return proto.CompactTextString(m) }
func (*ChatMessageOut) ProtoMessage()    {}

const Default_ChatMessageOut_FinalizeContext bool = true
const Default_ChatMessageOut_Type MessageType = MessageType_TEXT

func (m *ChatMessageOut) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ChatMessageOut) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *ChatMessageOut) GetFrom() *UserInfo {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChatMessageOut) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ChatMessageOut) GetContext() *UUID {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *ChatMessageOut) GetFinalizeContext() bool {
	if m != nil && m.FinalizeContext != nil {
		return *m.FinalizeContext
	}
	return Default_ChatMessageOut_FinalizeContext
}

func (m *ChatMessageOut) GetContents() string {
	if m != nil && m.Contents != nil {
		return *m.Contents
	}
	return ""
}

func (m *ChatMessageOut) GetType() MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_ChatMessageOut_Type
}

func (m *ChatMessageOut) GetTo() *MessageTarget {
	if m != nil {
		return m.To
	}
	return nil
}

type ChatMessageIn struct {
	Server           *string      `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	From             *UserInfo    `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Timestamp        *int64       `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	Context          *UUID        `protobuf:"bytes,4,req,name=context" json:"context,omitempty"`
	Contents         *string      `protobuf:"bytes,5,opt,name=contents" json:"contents,omitempty"`
	Type             *MessageType `protobuf:"varint,6,opt,name=type,enum=com.foxelbox.foxbukkit.chatlink.MessageType,def=0" json:"type,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChatMessageIn) Reset()         { *m = ChatMessageIn{} }
func (m *ChatMessageIn) String() string { return proto.CompactTextString(m) }
func (*ChatMessageIn) ProtoMessage()    {}

const Default_ChatMessageIn_Type MessageType = MessageType_TEXT

func (m *ChatMessageIn) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *ChatMessageIn) GetFrom() *UserInfo {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChatMessageIn) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ChatMessageIn) GetContext() *UUID {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *ChatMessageIn) GetContents() string {
	if m != nil && m.Contents != nil {
		return *m.Contents
	}
	return ""
}

func (m *ChatMessageIn) GetType() MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_ChatMessageIn_Type
}

func init() {
	proto.RegisterEnum("com.foxelbox.foxbukkit.chatlink.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("com.foxelbox.foxbukkit.chatlink.TargetType", TargetType_name, TargetType_value)
}
